---
title: "Taller 11"
author: 
  - Juan Sosa PhD, jcsosam@unal.edu.co
date: ""
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
---


1. El artículo *Direct Strut-and-Tie Model for Prestressed Deep Beams* (K. Tan, K. Tong y C.
Tang, en *Journal of Structural Engineering*, 2001:1076-1084) presenta mediciones de la fuerza
nominal de corte (en kN) para una muestra de 15 vigas de concreto. Los resultados son:

    580 400 428 825 850 875 920 550 575 750 636 360 590 735 950

    ¿Es adecuado utilizar la estadística t de Student para construir un intervalo de confianza de 99\% para la media de la fuerza de corte? Si es así, construya el intervalo de confianza. Si no, explique por qué.
    

2. En el artículo referido en el problema anterior, la fuerza compresiva cilíndrica (en MPa) fue medida
para 11 vigas. Los resultados fueron:

    38.43 38.43 38.39 38.83 38.45 38.35 38.43 38.31 38.32 38.48 38.50

    ¿Es adecuado utilizar la estadística t de Student para construir un intervalo de confianza de 95% para la media de la fuerza compresiva cilíndrica? Si es así, construya el intervalo de confianza. Si no, explique por qué.
    
3. ¿Verdadero o Falso? La distribución t de Student se puede utilizar para construir un intervalo de confianza para la media de cualquier población, en tanto que el tamaño muestral sea pequeño.

4. En 2000 fueron visitados 30 restaurantes de comida rápida entre los que se encontraban *Wendy's, McDonald's y Burger King* (*The Cincinnati Enquirer*, 9 de julio de 2000). Se registró el tiempo que transcurría entre que el cliente hiciera su pedido y la recepción del mismo. Los tiempos en los 30 restaurantes visitados fueron los siguientes:

    0.9 1.0 1.2 2.2 1.9 3.6 2.8 5.2 1.8 2.1 6.8 1.3 3.0 4.5 2.8 2.3 2.7 5.7 4.8 3.5 2.6 3.3 5.0 4.0 7.2 9.1 2.8 3.6 7.3 9.0

  a. Dé una estimación puntual de la media poblacional.
  b. ¿Cuál es el margen de error con 95% de confianza?
  c. ¿Cuál es la estimación por intervalo de confianza de 95% para la media poblacional?
  d. Analice el sesgo que puede encontrarse en esta población. ¿Qué sugeriría para la repetición de este estudio?
  
5. El costo promedio de la gasolina sin plomo en Grater Cincinnati es US 2.41 (*The Cincinnati Enquirer*,
3 de febrero de 2006). En una época de cambios en los precios, un periódico muestrea las gasolineras
y presenta un informe sobre los precios de la gasolina. Suponga que en los precios del galón de
la gasolina sin plomo la desviación estándar es US 0.15. Dé el tamaño de muestra $n$ que debe usar este
periódico para tener 95\% de confianza con cada uno de los márgenes de error siguientes.

a. Un margen de error de US 0.07.
b. Un margen de error de US 0.05.
c. Un margen de error de US 0.03.

6. En la industria farmacéutica la varianza en los pesos de los medicamentos es trascendental. Considere
un medicamento cuyo peso está dado en gramos y una muestra de 18 unidades de este medicamento,
la varianza muestral es 0.36.

a. Dé un intervalo de 90\% de confianza para estimar la varianza poblacional de los pesos de
este medicamento.
b. Proporcione un intervalo de 90\% de confianza para estimar la desviación estándar poblacional.
c. ¿Bajo que condiciones son válidos estos intervalos?

7. Un grupo de 12 analistas de seguridad proporcionó estimaciones, para el año 2001, de las ganancias
por acción de Qualcomm, Inc. (Zacks.com, 13 de junio de 2000). Los datos son los siguientes:

    1.40 1.40 1.45 1.49 1.37 1.27 1.40 1.55 1.40 1.42 1.48 1.63

  a. Calcule la varianza muestral de las estimaciones de ganancia por acción.
  b. Calcule la desviación estándar muestral de las estimaciones de ganancia por acción.
  c. Dé una estimación por intervalo de confianza de 95% para la varianza poblacional y para la desviación estándar poblacional.