---
title: "Taller 8"
author: 
  - Lina Buitrago PhD(c), labuitragor@unal.edu.co
  - Juan Sosa PhD, jcsosam@unal.edu.co
date: ""
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Un consultor que habitualmente evalúa un proceso de producción reporta el número de defectos importantes encontrados en cada artículo examinado. Sea $X$ el número de defectos importantes en un artículo seleccionado al azar. Se sabe que la función de distribución acumulada de $X$ es:
$$
F_X(x) = 
\begin{cases} 
0.00  \,,\,\,\,        x < 0; \\
0.06  \,,\,\,\, 0 \leq x < 1; \\
0.19  \,,\,\,\, 1 \leq x < 2; \\
0.39  \,,\,\,\, 2 \leq x < 3; \\
0.67  \,,\,\,\, 3 \leq x < 4; \\
0.92  \,,\,\,\, 4 \leq x < 5; \\
0.97  \,,\,\,\, 5 \leq x < 6; \\
1.00  \,,\,\,\, 6 \leq x    ; \\
\end{cases}
$$

a. Obtener la función de masa de probabilidad $f_X(x)$.
b. Graficar $f_X(x)$ y $F_X(x)$.
c. Calcular e interpretar $P(X=2)$, $P(X>3)$, $P(2\leq X\leq 5)$.
d. Calcular e interpretar el valor esperado de $X$.
e. Calcular e interpretar el coeficiente de variación $X$.

2. La variable aleatoria $X$ que representa el pH del agua (medido en una escala continua) de un proceso experimental de limpieza tiene la siguiente función de densidad de probabilidad:
$$
f_X(x) =
\begin{cases}
k\,(7-x)^2 \,,\,\,\, 5 < x < 7; \\
0          \,,\,\,\, \text{en otro caso}; \\
\end{cases}
$$

a. Demostrar que el valor de $k$ para que $f_X(x)$ sea una función de densidad de probabilidad auténtica es $k=3/8=0.375$.
b. Obtener una fórmula general para la función de distribución acumulada $F_X(x)$.
c. Graficar $f_X(x)$ y $F_X(x)$.
d. Calcular e interpretar $P(X=6)$, $P(X>6)$, $P(5.5\leq X\leq 6.5)$.
e. Calcular e interpretar la mediana de $X$.
f. Calcular e interpretar el valor esperado de $X$.
g. Calcular e interpretar el coeficiente de variación $X$.
h. Debido a un error de calibración del instrumento de medición todos los valores de la variable $X$ se deben disminuir 10\%. Calcular nuevamente el valor esperado y el coeficente de variación.

3. El porcentaje de individuos de una ciudad a favor de una medida económica es una variable aleatoria (v.a.) $X$ con la siguiente función de densidad de probabilidad (f.d.p.):
$$
f_X(x) = 
\left\{
\begin{array}{ll}
\theta x^{\theta-1},& \hbox{si $0<x<1$;} \\
0,                  & \hbox{en otro caso,}
\end{array}
\right.
$$
donde $\theta > 0$ es el parámetro que controla la f.d.p. de $X$.

a. ¿Cuál es la variable de estudio $X$? ¿Cuál es el rango de $X$?
b. Demostrar que $f_X(x)$ es una f.d.p. válida. 
c. Graficar la f.d.p. de $X$ para $\theta\in\{1/3, 1/2, 1, 2, 3\}$.
d. Encontrar una expresión general para el valor esperado de $X$.
e. Encontrar una expresión general para la varianza de $X$.
g. Encontrar una expresión general para el coeficiente de variación de $X$.
h. Encontrar una expresión general para la función de distribución acumulada (f.d.a.).
i. Encontrar una expresión general para la mediana de $X$.   